### ISSUE TITLE
Usage example does not work

### ISSUE THREAD

**Issue by Qrysto** [fcomb/redux-logger#10]
We cannot call `createLogger()` without parameters because in src/index.js line 4-5:

    function resolver(input) {
      const { dispatch } = input;
    ...

it will throw a "Cannot read property 'dispatch' of undefined" error.

**Comment by theaqua** [comment]
Oh, right. Fixed in 1.0.1.

**Comment by Qrysto** [comment]
thanks for the quick response :smiley:
