### ISSUE TITLE
Requesting update to use 'react-dom

### ISSUE THREAD

**Issue by WilliamHolmes** [fcomb/redux-logger#104]
React.findDOMNode is deprecated. Please use ReactDOM.findDOMNode from require('react-dom') instead.
```javascript
LogMonitor.prototype.componentWillReceiveProps = function componentWillReceiveProps(nextProps) {
    var node = _react.findDOMNode(this.refs.elements);
```

**Comment by theaqua** [comment]
Probably you want file an issue to [LogMonitor](https://github.com/gaearon/redux-devtools-log-monitor)?
