### ISSUE TITLE
basically made a node version

### ISSUE THREAD

**Issue by low-ghost** [fcomb/redux-logger#11]
threw together a quick node/server version of this. https://github.com/low-ghost/redux-node-logger. Nothing spectacular or noteworthy, but could be of interest.

**Comment by theaqua** [comment]
From [1.0.2](https://github.com/fcomb/redux-logger/releases/tag/1.0.2) you [can pass custom logger](https://github.com/fcomb/redux-logger#logger-object) by `options.logger`.

Is it fits your request or you can't implement node.js-logger by this option?

**Comment by low-ghost** [comment]
Actually, didn't see that as part of the options object. Seems like there's some room there, but as far as I can tell, replacing console wouldn't be the solution unless one were to write a console wrapper that supported
```js
console.log(`%c prev state`, `color: #9E9E9E; font-weight: bold`, prevState);
```
renderkid is close but there would still be a need to convert the color argument to a supported syntax and support customizing color choices (renderkid only supports a handful of css based/non-hex colors like 'red'). Also, node won't print the full object on a simple console.log, has to be stringified. I'm not sure writing a replacement console object would make the most sense there.

I think it'd be neat to have a sane default for server side console built in, basically detecting if it's a node console and using renderkid or something similar for formatting and color

**Comment by thom-nic** [comment]
I just ran into a similar situation... Basically attempting to run the my store code in node unit tests gave me this:
```
ReferenceError: window is not defined
      at node_modules/redux-logger/build/createLogger.js:43:33
```
So maybe I can add some code to detect `if (typeof window === 'undefined' ) // use node console`.  

But it would be cool if redux-logger attempted to detect browser vs node env by default.

**Comment by theaqua** [comment]
@thom-nic you can use [`logger` option](https://github.com/fcomb/redux-logger#logger-object).

@low-ghost I think, we can made a better implementation. Do you have any ideas in that way?

**Comment by epeli** [comment]
> Do you have any ideas in that way?

Just drop the window prefix and it should work.

    const console = logger || window.console;

to

    const console = logger || console;

This can of course break some really old browsers but I think people supporting those will polyfill it anyway.

**Comment by thom-nic** [comment]
I tried to replace `window.console` with node's `console` which worked, save for all of the styling that the logger does on the output.  This is what you get if you pass `{logger:console}` in node:
```
action init @ 11:25:58
%c prev state color: #9E9E9E; font-weight: bold { transmitter: 
   { transmitter: { label: '[unknown]', id: 0, line_cards: [] },
     inProgress: false,
     error: null } }
%c action color: #03A9F4; font-weight: bold { type: 'init' }
%c next state color: #4CAF50; font-weight: bold { transmitter: 
   { transmitter: { label: '[unknown]', id: 0, line_cards: [] },
     inProgress: false,
     error: null } }
—— log end ——
```

So simply passing a `logger: console` option doesn't exactly work as well as I hoped.

Would be cool if redux-logger could detect the node env and e.g. use ANSI terminal colors with Node's console.  I don't know if that's possible to do via the `logger` option since it looks like the given logger gets passed the already-formatted output.

**Comment by theaqua** [comment]
@epeli it's not a problem, you can pass node's `console` in `options.console`.
@thom-nic you're right, problems with formatting. I'll release new version on next week with message formatters.
