### ISSUE TITLE
Batch actions

### ISSUE THREAD

**Issue by pauldijou** [fcomb/redux-logger#113]
Sometimes, you need to reduce several actions at once (to optimize and prevent multiple renders in React for example). It's mostly done by dispatching one action which payload is an array of actions which will be reduced at the same time.

Is there a way to log such use case? Right now, it only logs the batch action itself. I would like to at least log all the batched actions. Even better would be to display where the batch starts and where it ends.

I was thinking about doing it inside the `actionTransformer`:

- log the beginning of the batch
- log all batched actions from the payload of the action
- return the batch action itself so it is also logged and indicate the end of the batch

But maybe you have a better way to handle it?

Cheers

**Comment by smashercosmo** [comment]
Have a look a #116

**Comment by theaqua** [comment]
Solved by #116.

**Comment by pauldijou** [comment]
Thanks a lot.
