### ISSUE TITLE
actions that cause errors do not log next state

### ISSUE THREAD

**Issue by cappslock** [fcomb/redux-logger#114]
Bear with me :)

If you dispatch an action that has a side effect which causes an error to thrown, the next state for the action is not logged, even though the state may have changed.

I suspect this is not logged because the assumption is that the reducer failed and therefore did not change the state, but you see this happen a lot when an action is dispatched that, for example, causes a React component to render which itself is throwing an error. In this case, the state actually has been changed: you can see this by inspecting previous state of the next dispatched action.

I would suggest that next state still be logged if an error is triggered. I am happy to create a PR with a unit test and this change, if it is a welcome change.

**Comment by theaqua** [comment]
Yeah, PR is welcome :clap:

**Comment by cappslock** [comment]
Closing, fixed by #115
