### ISSUE TITLE
Redux-logger and redux-batched-actions

### ISSUE THREAD

**Issue by smashercosmo** [fcomb/redux-logger#116]
I made a [gist](https://gist.github.com/smashercosmo/6dc9c26ce1e2e3dafde5) of how to tune redux-logger to work nicely with redux-batched-actions. May be worth adding to examples section). Here is before/after [example](http://oi66.tinypic.com/21n4pl2.jpg).

**Comment by theaqua** [comment]
[Added](https://github.com/fcomb/redux-logger/blob/master/README.md#log-batched-actions), thank you!
