### ISSUE TITLE
Options documentation

### ISSUE THREAD

**Issue by ericelliott** [fcomb/redux-logger#118]
I got a little lost on the options object, wondering whether or not the options object docs ended. Maybe it would be useful to group them together into an encapsulated interface? e.g., using [rtype](https://github.com/ericelliott/rtype):

```js
interface OptionsObject {
  level = 'log': 'log' | 'console' | 'warn' | 'error' | 'info',
  duration = false: Boolean, // Print the duration of each action?
  timestamp = true: Boolean, // Print the timestamp with each action?
  colors: ColorsObject, // Object with color getters. See the ColorsObject interface.
  logger = window.console: LoggerObject, // Implementation of the `console` API.
  logErrors = true: Boolean, // Should the logger catch, log, and re-throw errors?
  // ...
}
```

**Comment by theaqua** [comment]
Yeah, at now options documentation is kinda weird. `rtype` looks good, reminded me Scala models.
I'll rewrite documentation in 2 days, thanks for the idea!
