### ISSUE TITLE
Proposal for slightly better Immutable stateTransformer example in the docs

### ISSUE THREAD

**Issue by landabaso** [fcomb/redux-logger#119]
Please consider using this piece of code for the "transform Immutable objects into JSON" example in the docs:

```
const stateTransformer = (state) => {
    let newState = {};

    if (typeof state === "object" && state !== null && Object.keys(state).length) {
        for (var i of Object.keys(state)) {
            if (Immutable.Iterable.isIterable(state[i])) {
                newState[i] = state[i].toJS();
            } else {                      
                newState[i] = stateTransformer(state[i]);
            }                             
        }                                 
    } else {                              
        newState = state;                 
    }                                     
                                          
    return newState;                      
} 
const loggerMiddleware = createLogger({ stateTransformer }); 

```

The current example is fine when the immutable objects are at the highest level. However, in many occasions it may be the case that immutable objects will be set in deeper levels (specially when doing reducer composition with combineReducers). The proposal above goes through all nested objects recursively.

**Comment by theaqua** [comment]
And where is proposal above?…

**Comment by landabaso** [comment]
I suggest that the the section in the docs here :
https://github.com/fcomb/redux-logger#transform-immutable-objects-into-json

shows the peace of code pasted in my comment above.

**Comment by theaqua** [comment]
Oh, yes, sorry.

Thanks, updated!
