### ISSUE TITLE
Timestamp is wrong

### ISSUE THREAD

**Issue by ffxsam** [fcomb/redux-logger#125]
The timestamp always seems to start at 16:00:00.

**Comment by toxickg** [comment]
Could you provide some details on this problem?

**Comment by theaqua** [comment]
Don't understand. Can you explain?

**Comment by ffxsam** [comment]
When I reload the page and start dispatching actions, the timestamp always starts at 16:00:00 (4pm). Should it actually be my current system time?

![title_here](https://cloud.githubusercontent.com/assets/12532733/12859226/a908dfa2-cc09-11e5-87d9-c9b9cba51c34.png)

**Comment by ffxsam** [comment]
The logger code makes a decision between using `Date.now()` and `performance.now()`, though the two are completely different things. `Date.now()` is a UNIX epoch timestamp. `performance.now()`, I honestly have no idea what it is. I think it's the number of milliseconds the web page has been loaded.

**Comment by theaqua** [comment]
No, that code used for `duration` option.

To be honest, I don't know to fix your problem, we just [use `Date.now()`](https://github.com/fcomb/redux-logger/blob/master/src/index.js#L69) for the current time.

**Comment by ffxsam** [comment]
It's not using `Date.now` for the time. Look at this line:

https://github.com/fcomb/redux-logger/blob/4a00216b77da77ef01535b75abc9d3f2fbfb7d43/src/index.js#L6

Since `performance` exists in most modern browsers, it uses that instead of `Date`. Go ahead and open a JavaScript console and type `Date.now()` and hit enter, compare that value with what you get when you type `performance.now()`. They're two totally different things.

So the question is: what is the redux logger supposed to show? The current time?

**Comment by theaqua** [comment]
Please, read code more attentively. Function `timer` used only for `duration` option, for current time we using `new Date()`, I have link in my past message.

**Comment by ffxsam** [comment]
Then please explain the image above, where it says `@ 16:00:03.083`. This is a bug, as it was not 4pm when those actions were run.

**Comment by ffxsam** [comment]
BTW, `duration` is `false` by default, so it's not the duration that's printing. I don't know how to explain this any clearer.

**Comment by ffxsam** [comment]
Here's the problem:

https://github.com/fcomb/redux-logger/blob/4a00216b77da77ef01535b75abc9d3f2fbfb7d43/src/index.js#L121

It's setting `logEntry.started = timer.now()`, and then later it's treating that value as if it were a date/time:

https://github.com/fcomb/redux-logger/blob/4a00216b77da77ef01535b75abc9d3f2fbfb7d43/src/index.js#L72

Does that make sense now?

**Comment by ffxsam** [comment]
PR #131 fixes this.

**Comment by theaqua** [comment]
You're right! Thank you.
