### ISSUE TITLE
`stateTransformer` does not exist in type `ReduxLoggerOptions`

### ISSUE THREAD

**Issue by datatypevoid** [fcomb/redux-logger#126]
While trying out the `transform Immutable objects into JSON` code from the README.md, I get the error

```
error TS2345: Argument of type '
    { stateTransformer: (state) => {
        return {
           . . .
        }
    }'
is not assignable to parameter of type 'ReduxLoggerOptions'. Object literal may only specify known properties, and 'stateTransformer' does not exist in type 'ReduxLoggerOptions'.
```

**Comment by theaqua** [comment]
TypeScript?

**Comment by datatypevoid** [comment]
Yeah sorry, I was passing out for the night when I opened this. Newest Node and NPM, Win10x64

**Comment by arusakov** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/7693.
In the near future will be in redux-logger.d.ts

**Comment by theaqua** [comment]
@datatypevoid is case solved?

**Comment by theaqua** [comment]
Reopen if not.
