### ISSUE TITLE
Fails when Symbols are used for action types.

### ISSUE THREAD

**Issue by davidmason** [fcomb/redux-logger#128]
It makes sense to use `Symbol()` for action type identifiers, so there is no chance of accidentally using the same type identifier for two different actions. The logger fails when it tries to append the symbol as a string value.

This can be easily fixed by wrapping `formattedAction.type` in `String(...)` or by adding `.toString()` to the end.

The whole line would become: https://github.com/fcomb/redux-logger/blob/master/src/index.js#L74

```javascript
const title = `action ${String(formattedAction.type)}${timestamp ? formattedTime : ``}${duration ? ` in ${took.toFixed(2)} ms` : ``}`;
```

**Comment by davidmason** [comment]
@fcomb this should be a quick fix, just wrap one expression in a function. Want me to make a PR, or can you just do a quick edit on github?

**Comment by davidmason** [comment]
I made a quick PR for this anyway: https://github.com/fcomb/redux-logger/pull/129

**Comment by theaqua** [comment]
As [I said](https://github.com/fcomb/redux-logger/pull/129#issuecomment-182743693), `actionTransformer` for the rescue.

**Comment by theaqua** [comment]
I added [receipt](https://github.com/fcomb/redux-logger#transform-symbol-action-type-to-string) to docs 💃

**Comment by davidmason** [comment]
Nice. In my case I also stuck a console.warn into the transformer when it finds non-symbol action types, to help me get everything consistent :)
