### ISSUE TITLE
Add option to show diff between prev state and next state

### ISSUE THREAD

**Issue by jonaskello** [fcomb/redux-logger#132]
I find that when troubleshooting I want to see what changes the action caused in the store. So if it was somehow possible to log the delta between prev and next state that would be great. 
Perhaps the diffing should not be built-in in the logger, but instead we could provide an option function that receives both prev and next state and can output the desired diff. Today the state transform option functions only receive either prev or next state, not both.

**Comment by epeli** [comment]
https://github.com/fcomb/redux-diff-logger ?

**Comment by jonaskello** [comment]
@epeli Looks good! 
However I think it still would be nice if we could get the possibility to extend redux-logger to show diffs.

**Comment by jonaskello** [comment]
Tested redux-diff-logger out and seems it does not support Immutable objects well. If we could invert it so the diffing logic is something we can provide from the outside then I could add Immutable support and other things myself.

**Comment by theaqua** [comment]
I suggest continue a discussion in #136.
