### ISSUE TITLE
What's the best way to compartmentalize redux-logger messages?

### ISSUE THREAD

**Issue by cageygee3** [fcomb/redux-logger#133]
redux-logger will be very helpful for my project, but I'm finding that the output of messages is difficult to manage. My console window is polluted with action messages, causing me to miss legitimate warnings and errors. Filtering (in Chrome) doesn't seem to help, as there's no way to filter out the logging groups; even if I click the "Errors" button in the filter toolbar, the redux logging groups still appear.

I would love to keep all the log messages, but have them directed to another location that I can check on demand, that way my console remains useful. Is it possible to redirect redux-logger messages to another DevTools panel? Or to another entry in the `<top frame>` drop-down list?

My only idea at this point is to write a Chrome extension that exports a very thin console wrapper object, which would be passed to redux-logger. All the messages would be proxied to the console as usual, except now they'd be coming from a browser extension, which means they'd only be visible if you selected the extension from the `<top frame>` drop-down list. (I'm assuming that's how that works.)

I'd rather not embark on this if there's an easier way to do this filtering. Thoughts? Any ideas on a simple solution would be greatly appreciated. :smile:

**Comment by theaqua** [comment]
In my project I using `collapsed` option, it's very useful as for me. Messages built in structured table.

![image](https://cloud.githubusercontent.com/assets/775692/13205794/337f6a58-d901-11e5-9b30-8dcd86db0ef6.png)

**Comment by cageygee3** [comment]
Right, I'm using the collapsed option as well, but I still can't filter out
those groups from appearing in the console.

**Comment by theaqua** [comment]
But how are you can miss errors and warnings? They have different colors than black logger. And you can use `predicate` option to filter unnecessary messages (`blur` and `touch` for every field in `redux-form`, for example). If anyone wants to make extension — feel free, I'll add method in core.

**Comment by cageygee3** [comment]
My project produces a lot of redux logging messages because the redux state changes as the mouse moves over the page. All those messages fill up the console and push the errors/warnings off the screen, so that's why I've been missing them.

**Comment by theaqua** [comment]
Seems like `predicate` can resolve your problem.

**Comment by cageygee3** [comment]
No, it doesn't really solve the problem, because I want to keep all the messages for debugging later. I just don't want them in my main console window.

**Comment by cageygee3** [comment]
It doesn't seem like this problem has been solved in general. The best solution I've seen is to group *everything* into a single logging group, but that won't work here because the code can never call `console.groupEnd()` because actions will be emitted for as long as the page is open.

If I figure out a worthwhile solution at any point, I'll post it here.

**Comment by zach-is-my-name** [comment]
@evgenyrodionov What's the best way to filter from redux-form?

I gave it:
`predicate:(getState, action) => action.type !== @@redux-form/FOCUS || @@redux-form/BLUR || @@redux-form/FOCUS`

Which was my best interpretation based on the recipe:
`predicate: (getState, action) => action.type !== AUTH_REMOVE_TOKEN`

**Comment by evgenyrodionov** [comment]
@zach-is-my-name `!action.type.includes('@@redux-form')`

**Comment by zach-is-my-name** [comment]
Perfect timing. Best wishes, thanks again.

**Comment by jordanpapaleo** [comment]
Hi - I am able to make the individual sections be logged in debug like this: 

```
middleware.push(createLogger({
      collapsed: false,
      level: {
        prevState: 'debug',
        action: 'debug',
        nextState: 'debug',
        error: 'error'
      }
    }))
```

Is there a way to print the main `action SET_APP_STATE @ 11:57:00.155` message to the console as a debug as well?

Thanks

**Comment by evgenyrodionov** [comment]
@jordanpapaleo hi! Don’t understand your question, can you explain your use case?

**Comment by jordanpapaleo** [comment]
Thanks for the quick reply! I love the details available in the logging from redux-logger.  We have a extremely large app and the console can get a little crowded.  We feel the pain when we are trying to specifically log out and debug.  In chrome dev tools we can filter what is displayed in my console, super cool. 

![image](https://user-images.githubusercontent.com/1728807/32121198-79a8dcec-bb10-11e7-8056-5fe5c2a832ab.png)

I would like to set where redux-logger reports to.  Right now it appears to be showing on the `console.log` view.  I would love to set a flag that will set it to only report under a console.debug as that only shows up when I have the console set to show verbose debugging.  I am able to get the prevState, action, and nextState to log in debug mode by this config:

```javascript
createLogger({
      collapsed: false,
      logger: console,
      level: {
        prevState: 'debug',
        action: 'debug',
        nextState: 'debug',
        error: 'error'
      }
    })
```

Is there a way to set the entire message to be logged out as a console.debug allowing me to only show them when I have chrome devtools showing the console.debug messages (verbose mode)

Thank you for your time :)

**Comment by jordanpapaleo** [comment]
Ill try to dig into the code this weekend if I get some free time and take a look as well

**Comment by kaushikwavhal** [comment]
1.) I think the OP is pointing out that the actions cannot be filtered out by chrome dev tools when you type something in the filter box and it gets in the way of debugging things when even after filtering you still see a clogged console filled with many logs.

2.) Another similar issue is, in the filtered view, if you filter out a particular action name, you can see it but expanding it does nothing except the arrow changes to down arrow. One would want to filter out a particular action in the huge list of actions but even if Point 1 worked as expected, you wouldn't be able to see any data from the filtered action log.

**Comment by joseMakeen** [comment]
This should be open, this issue is still there

**Comment by FranciscoG** [comment]
exactly what @kaushikwavhal said.  It's really annoying that when I put anything into the filter input and I still see redux-logger logs. And I definitely am not putting any filter text that would match anything in the redux-logger logs

Also, why is it that they still show up when I hide all logging. It's very frustrating.
![Screen Shot 2021-05-20 at 8 36 44 AM](https://user-images.githubusercontent.com/557684/118998250-8549fd00-b946-11eb-9a72-5b5e28284ddf.png)
