### ISSUE TITLE
Support for FSA

### ISSUE THREAD

**Issue by pke** [fcomb/redux-logger#138]
I recently converted my project to use [FSA](https://github.com/acdlite/flux-standard-action). Mainly because it provides a common way to detect errornous actions.
The logger outputs do not display `error` actions correctly though. They appear in black, just as every action that did not throw during creating or reducing.

I have 2 proposals:

1. `FSA` with `error === true` are logged using the error color
2. If the action has a `payload` then display that flattened so we do not have to manually open the entry to see the payload content.

If those changes would be ok for you, I'd create a PR.

**Comment by theaqua** [comment]
Hello!

1) you can use `colors` or even `level` option
```js
const logger = createLogger({
  level: ({ error = false }) => error ? `error` : `log`,
});
```

2) you can use `actionTransformer` option
```js
const logger = createLogger({
  actionTransformer: ({ payload, ...action }) => ({ ...action, ...payload }),
});
```

**Comment by pke** [comment]
@theaqua ah cool!
