### ISSUE TITLE
Errors in reducers are not logged

### ISSUE THREAD

**Issue by pke** [fcomb/redux-logger#139]
I have a `reducer` that throws (because the payload was not checked correctly). However the logger does not seem to catch this or isn't it supposed to?

![image](https://cloud.githubusercontent.com/assets/164625/13569715/e9c20c9e-e469-11e5-93e6-e58667d030e2.png)

**Comment by theaqua** [comment]
Can you make a PR? I think it will be good if we throw errors of reducer.
