### ISSUE TITLE
Q: How to use in debug mode only without changing the source code?

### ISSUE THREAD

**Issue by ron23** [fcomb/redux-logger#140]
I saw this recepie: 
log only in dev mode

```
import thunk from 'redux-thunk';

const middlewares = [thunk];

if (process.env.NODE_ENV === `development`) {
  const createLogger = require(`redux-logger`);
  const logger = createLogger();
  middlewares.push(logger);
}

const store = compose(applyMiddleware(...middlewares))(createStore)(reducer);
```

But I don't want my production code to have "if debug" all over the place (I'm using a few debug tools). 
Is there a way I can get the same result without changing the source code? 
I'm using gulp and webpack to build my project.

**Comment by theaqua** [comment]
Nope, I don't know other technique.
