### ISSUE TITLE
Wrong state logged

### ISSUE THREAD

**Issue by chvanikoff** [fcomb/redux-logger#143]
Hi,
On the screenshot you can see 2 actions logged:
![logged actions](http://puu.sh/nUpjq/1e868ce405.png)
but in the 1st action's log there's a state which is actual only when 2nd action occurs. Particularly, `ws.channels` is empty object before and after 1st action but in logs it appears as it is after 2nd action. `Object {}` is a result of `console.log(state.channels)` before each of the actions action. Here's a complete reducer's code:
```js
const initialState = {
  socket: null,
  channels: {}
};

export default function reducer(state = initialState, action = {}) {
  switch (action.type) {
    case "SOCKET_CONNECTED":
      console.log(state.channels);
      return {
        ...state,
        socket: action.socket
      };
    case "CHANNEL_JOINED":
      console.log(state.channels);
      let channels = state.channels
      channels[action.name] = action.channel
      return {
        ...state,
        channels: channels
      }
    default:
      return state;
  }
}
```
version of redux-logger used is 2.6.1, redux - 3.3.1
Please let me know if I can provide u with any other information that can help to identify source of the issue - I'm very new to the whole JS ecosystem and don't know what else can be helpful here.

**Comment by theaqua** [comment]
Probably because you're mutating `state.channels` in `CHANNEL_JOINED`.

**Comment by chvanikoff** [comment]
Thank you, rewriting to
```js
case "CHANNEL_JOINED":
      return {
        ...state,
        channels: {
          ...state.channels,
          [action.name]: action.channel
        }
      }
```
fixed the issue (is it correct rewriting of what I previously used?). But it's still not clear to me why this happen when I mutate the channels property, from what I've seen I was sure actions are dispatched in order and the mutation occurs after the first action. Can you suggest anything related to read?

**Comment by theaqua** [comment]
I don't have close links right now, but I summon @gaearon for help if he want.
