### ISSUE TITLE
Default title color black invisible in Chrome Dev Tools Dark theme

### ISSUE THREAD

**Issue by Cottin** [fcomb/redux-logger#144]
Don't know if you'll consider this an issue but in Chrome there is now a dark theme for dev tools:

![image](https://cloud.githubusercontent.com/assets/4736419/14098962/88f0b446-f581-11e5-9204-0c521468ee21.png)

With it, it's hard to see title of actions being logged:

![image](https://cloud.githubusercontent.com/assets/4736419/14098983/b4fe3b3a-f581-11e5-83b3-ddbc22e5243f.png)

Easily fixed by using options:
```
const logger = createLogger({colors: {title: false}})
```

Which gives: 
![image](https://cloud.githubusercontent.com/assets/4736419/14099009/01769994-f582-11e5-830c-7c5109e667e8.png)

You think it's worth having another default instead of black? Or if not, is it worth mentioning in the readme if more and more people starts using the dark theme?

**Comment by Cottin** [comment]
Note: in my simple fix above using `false` everything turns white. If you want the default colors but ONLY want to change the title color you'd have to do this as far as I understand:

```
	logger = createLogger
		colors:
			title: -> '#FFFFFF'
			prevState: -> '#9E9E9E'
			action: -> '#03A9F4'
			nextState: -> '#4CAF50'
			error: -> '#F20404'
```
(coffee-script)

**Comment by k-zakhariy** [comment]
would be great to have dynamic title colors, for example if error -> title color will be in error color #F20404
