### ISSUE TITLE
Demo is broken because of reducer bug with Symbols

### ISSUE THREAD

**Issue by billyjanitsch** [fcomb/redux-logger#19]
Neither of the array buttons in the [demo](http://fcomb.github.io/redux-logger/) work because of [this bug](https://github.com/acdlite/redux-actions/issues/20) in `redux-actions`. The actions are dispatched and logged correctly, but the reducer doesn't transform the state correctly when the action type is a Symbol. No problems with `redux-logger` itself -- just letting you know.

**Comment by theaqua** [comment]
Wow, thanks, didn't pay attention. I don't usually use Symbols (same reason https://github.com/acdlite/redux-actions/issues/20#issuecomment-134340125), just added support in #14 and updated demo.

I remove Symbol() from demo.

**Comment by billyjanitsch** [comment]
FYI, this issue was just fixed in `redux-actions@0.8.0`, so the old demo should be fine if you bump the dep! :)
