### ISSUE TITLE
Don't crash in browsers without `console.group`

### ISSUE THREAD

**Issue by gaearon** [fcomb/redux-logger#2]
It's fair to assume `console.log`, but any other method should only be used with a fallback to `console.log`.

**Comment by theaqua** [comment]
I saw this issue and agreed with it, so I go add fallback.
Then I download Firefox 20, `console.group` works well. Hm, download Firefox 8, works well too. Interesting, maybe I need old Chrome. So I went to [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Console/group) and check browser support.

Surprisedly it works from Chrome@2 (!), Firefox@4 (!), Safari@4 (!), but IE@11. Funny.

I [fix](https://github.com/fcomb/redux-logger/commit/df93f4b771a158aedd12103dbd890ee01938de84) it, thanks for reporting.
