### ISSUE TITLE
Clarify that logger needs to come last in middleware chain

### ISSUE THREAD

**Issue by gaearon** [fcomb/redux-logger#20]
Otherwise it'll log thunks and promises but not actual actions.

**Comment by theaqua** [comment]
Right. Added in README.
https://github.com/fcomb/redux-logger/commit/cb34a562d2cda941a6cf90d7011c90231096cfcc

**Comment by RavenHursT** [comment]
Question... why not just officially support this as a configurable option?

I find it nice to know which thunk-functions were dispatched, that eventually led to the _actual_ Redux actions that were dispatched...

![image](https://user-images.githubusercontent.com/496983/99006944-dcd75e00-2508-11eb-80de-8e3d16252849.png)

Seems like it wouldn't be _too_ much work to allow it to be configurable to `logThunkDispatches: true/false` then replace `undefined` w/ something as simple as `THUNK`

Then maybe it might even get picked up by the Chrome DevTools Redux extension?
