### ISSUE TITLE
"log only in dev mode" doesn't work

### ISSUE THREAD

**Issue by burtyish** [fcomb/redux-logger#26]
The example code from https://github.com/fcomb/redux-logger#log-only-in-dev-mode didn't work for me. I still get logging on my deployed staging environment. 

```
const __DEV__ = true;

createLogger({
  predicate: (getState, action) => __DEV__
});
```

How/why does this code even work? What am I missing? I mean why would it work locally and not on production? Is it a webpack thing? (I'm using browserify)

Thanks!

**Comment by brandonlilly** [comment]
Presumably you'd have it set up so __DEV__ is false in production.

**Comment by burtyish** [comment]
@brandonlilly would you elaborate? Maybe give an example of how you'd do that.

**Comment by luisrudge** [comment]
@burtyish https://github.com/petehunt/webpack-howto#6-feature-flags

**Comment by burtyish** [comment]
I see. I'll have to find a way to something like that with Browserify then.

**Comment by luisrudge** [comment]
easy: https://github.com/hughsk/envify

**Comment by burtyish** [comment]
Right. Global variable. Thanks.

**Comment by burtyish** [comment]
Sorry, I guess I'm missing something.
After taking a closer look, it appears that envify would only apply to a server-side app. AFAIK there is no `process.env` when running in the browser.

**Comment by nlitwin** [comment]
All of the Webpack configuration, Babel transpiling, etc. happens in Node. It's at that point that envify replaces process.env with the values. So your frontend code will end up with strings instead of process.env.

**Comment by burtyish** [comment]
Right. I've since gotten a better understanding of the process. Thanks.

**Comment by nlitwin** [comment]
Awesome! Just figured I'd add it in case other people had a similar question and stumbled upon this thread :)
