### ISSUE TITLE
Message upgrade redux-logger

### ISSUE THREAD

**Issue by MrEfrem** [fcomb/redux-logger#28]
I receive message :
```
redux-logger updated to 1.0.0 and old `logger` is deprecated, check out https://github.com/fcomb/redux-logger/releases/tag/1.0.0
```
but in packages.json
```
...
"redux-logger": "^1.0.8"
...
```

**Comment by epeli** [comment]
I think the old interface is still there in 1.0.0 but you should not just use it.

**Comment by MrEfrem** [comment]
There are I used an old way of initialization through:
 import loggerMiddleware from 'redux-logger';
I remade on that that is provided to documentation and warning disappeared.

**Comment by theaqua** [comment]
Yeah, I wrote about this in 1.0.0 release, which introduces options.
https://github.com/fcomb/redux-logger/releases/tag/1.0.0
