### ISSUE TITLE
Support for log level

### ISSUE THREAD

**Issue by idolize** [fcomb/redux-logger#3]
It would be awesome if you could add support for custom logging frameworks.

For example, I use the library [loglevel](https://github.com/pimterry/loglevel) because it allows me to configure what logs show up on the console with specific levels you can even change at runtime.

**My use case is that I would love to see these logs in production to help diagnose an issue (where I likely don't have [redux-devtools](https://github.com/gaearon/redux-devtools) available), but I don't want them always showing up on the console without opting-in (I have a lot of actions happening all the time and it would clutter things up).**

So, ultimately, what I would like to do is have the logs coming in as `log.debug`, or some level that is not shown by default, then I can turn them on at runtime with `log.setLevel('debug')` on the console -- suddenly I can see all my debug spew!

**Comment by qimingweng** [comment]
This would be great

**Comment by theaqua** [comment]
I agree. I think we can implement `applyLogger` function (#1 will be solved too) which accepts logger implementation as argument. Then we pass `applyLogger` to `applyMiddleware` and now we see redux's middleware-like logger :)

Will release on this or next week.

**Comment by theaqua** [comment]
Released!
https://github.com/fcomb/redux-logger/releases/tag/1.0.0

**Comment by idolize** [comment]
@theaqua This is great! but unfortunately it still does not quite provide the functionality I am looking for. Hard-coding `console` means that I cannot use something like `loglevel` (the library linked), which wraps the console methods.

I'll add a quick (non-breaking) PR to fix this if you don't mind :smile:

**Comment by theaqua** [comment]
@idolize oh, right, I forgot implement this. Big thanks for PR!

**Comment by idolize** [comment]
Awesome!! Thanks @theaqua

**Comment by jonaskello** [comment]
I tried with loglevel like this:

```
import * as log from "loglevel";
import * as createLogger from "redux-logger";
const logger = createLogger({ collapsed: true, logger: log });
```

It works but the entries are not collapsed anymore. Anyone has a pointer how to configure this?
