### ISSUE TITLE
Can't handle Action type as Symbol

### ISSUE THREAD

**Issue by dlwalsh** [fcomb/redux-logger#36]
I define my action types as symbols. e.g.

```js
export const ROOT_DID_MOUNT = Symbol('ROOT_DID_MOUNT');
```

which produces the following:

```
Uncaught TypeError: Cannot convert a Symbol value to a string
```

This appears to be a 1.0.9 -> 2.0.0 regression, as this was not an issue previously.

**Comment by dlwalsh** [comment]
OK, I've found a workaround. But it would be great if this wasn't necessary.

```js
const logger = createLogger({
    actionTransformer: (action) => Object.assign({}, action, {
        type: action.type.toString()
    })
});
```

**Comment by gaearon** [comment]
Note though that we don't recommend using Symbol action types because you can't (de)serialize them.

**Comment by dlwalsh** [comment]
Fair enough. Though I'm sure I adopted the practice from an online example.

I'll change them to strings. Thanks.

**Comment by theaqua** [comment]
It's not workaround, it's better management of action transforms. Earlier (#14), but other users want to control by themselves (#31), (#33), so we release [2.0.0](https://github.com/fcomb/redux-logger/releases/tag/v2.0.0) with that feature and, of course, with a note about transforms in Breaking changes section.
