### ISSUE TITLE
Add possibility to bypass logging

### ISSUE THREAD

**Issue by wizardzloy** [fcomb/redux-logger#4]
It would be great to have an option to bypass the logging by specifying a `predicate` function that accepts `getState` and `action` and returns `false` if we don't want to log or `true` otherwise;
```javascript
const logger = createLogger({
  predicate: (getState, action) => action.type !== AUTH_REMOVE_TOKEN
});
```

**Comment by theaqua** [comment]
Implemented by #5, will released in 1.0.0.
