### ISSUE TITLE
Fine grained control over `level`

### ISSUE THREAD

**Issue by arturmuller** [fcomb/redux-logger#54]
Hey — thanks for an awesome package! :+1:

I was wondering whether it is (would be?) possible to have fine grained control over which actions output as `log`, and which are `warn` or `error`. For instance, I would like to have actions with `action.error === true` to output as `error` even if by default I use `log`.

**Comment by toxickg** [comment]
Thanks for the suggestion, @arturmuller.

Currently it's not possible to log at different level depending upon `action.error` (or any other action's property). Let's think about solutions to this one...

**Comment by arturmuller** [comment]
Righto. From an API perspective, what do you think about this:

Make the level option able to accept an array of objects specifying a level and test function. The function gets action as an argument and if it returns true the specified level will be used. For example:

```js
const logger = createLogger({
  level: [
    {
      level: 'error',
      test: (action) => action.error,
    }
  ]
});
```

If none of the conditions are met it just falls back to `log`.

**Comment by arturmuller** [comment]
I guess you could also do:

```js
const logger = createLogger({
  level: {
    error: (action) => action.error
  }
});
```

...just rely on the object key to define the level and the test is its value. I guess it reads a bit nicer because you don't duplicate the `level` key.

**Comment by arturmuller** [comment]
BTW I see that you have assigned yourself to the issue so if you want to look into it yourself that would obviously be great, but if you want, I am happy to submit a PR.

**Comment by toxickg** [comment]
@arturmuller, a pull request is welcome, sure! :+1:

I've actually come up with something similar to the latter suggestion you've proposed. But here are some points to take into account:

1. Custom log level (not just `error`, `warn`, `log`).
2. Currently `level` is expected to be a string and this behavior should be kept.
3. A case when many of the supplied log level types are satisfied, for example:

```javascript
const logger = createLogger({
  level: {
    error: action => action.error.code === '403',
    warn: action => action.response === '',
    myCustomLevel: action => action
  }
});
```

Should the action be logged multiple times in case all of the conditions are satisfied? Well, probably, that is OK (it's the user who decides what to log)...

On the other hand, we could prioritize the logging by declaration order. So, if `error.code` is `403` the action is logged with `error` level, if it's not `403` then the following predicate is checked, etc.

**Comment by arturmuller** [comment]
Hey. Ok, cool. Points 1, 2 — yep, we're on the same page here.

With number 3, what I originally imagined is the second thing you described. It would use the first level that returns true. I think it doesn't really make sense to log something twice. But that would mean we would have to use the array version of the API because I think JS doesn't guarantee the order of keys in an object.

So it's either an array, but then you have the level-inside-of-level thing (which is ugly), or — new idea — a completely separate option for levels based on actions. Can't figure out what that would be called though. Any ideas?

(A nice side-effect of having a separate option would be that you can specify a base level with the `level` option, but you can still specify special cases. I think that could be useful.)

What do you think?

**Comment by toxickg** [comment]
We should also remember about `predicate` option, that is already used to resolve logging behavior!
