### ISSUE TITLE
How to disable redux-logger in production build?

### ISSUE THREAD

**Issue by mewben** [fcomb/redux-logger#6]

**Comment by wizardzloy** [comment]
my proposal https://github.com/fcomb/redux-logger/issues/4 will solve the issue. You would be able to define custom `predicate` function that is called before the logic of the `logger` takes place. If this  function call returns `false` logging would be bypassed.
````javascript
const logger = createLogger({
  predicate: (getState, action) => ! conf.production
});
const createStoreWithMiddleware = applyMiddleware(logger)(createStore);
````

**Comment by slava-sh** [comment]
Here is a way not to apply the middleware at all:
```js
const middleware = [
  ... other middleware ...
  DEBUG && logger,
].filter(Boolean);
const createStoreWithMiddleware = applyMiddleware(...middleware)(createStore);
```

**Comment by mewben** [comment]
Thanks @slava-sh

**Comment by gaearon** [comment]
It's better to do this with explicit `if` so your module bundler can cut the dead code: https://github.com/rackt/redux/issues/581#issuecomment-133187076

**Comment by theaqua** [comment]
I agree with @gaearon, it's not library's part, but your workflow build.

**Comment by mewben** [comment]
Thanks @gaearon

**Comment by maksad** [comment]
@gaearon 
Thanks :+1:

**Comment by aray12** [comment]
I know this is old, but what have people done for logging server-side rendering? The logs looks great in the browser, but I'd prefer to just turn them off server-side

**Comment by greyvugrin** [comment]
@aray12 
We've adopted the following:
```
let middleware = [ thunk ]
// Only the client has a window object, so only put the logger if the window is set
if (typeof(window) !== 'undefined') {
  middleware = [ ...middleware, createLogger() ]
}
```
Basically added a clause to only add the logger if we're sure we're in the client.

**Comment by dhilt** [comment]
Official redux doc (http://redux.js.org/docs/api/applyMiddleware.html#tips) says:

```
let middleware = [ a, b ]
if (process.env.NODE_ENV !== 'production') {
  let c = require('some-debug-middleware')
  let d = require('another-debug-middleware')
  middleware = [ ...middleware, c, d ]
}

const store = createStore(reducer, preloadedState, applyMiddleware(...middleware))
```

How to inject NODE_ENV in webpack build process (http://dev.topheman.com/make-your-react-production-minified-version-with-webpack/):

```
module.exports = {
  ...
  plugins:[
    new webpack.DefinePlugin({
      'process.env':{
        'NODE_ENV': JSON.stringify('production')
      }
  }),
  ...
```

**Comment by azappella** [comment]
I know this is closed, but in case someone is interested, this is how to solve it: 

in webpack.config.js
```
if (env === 'production') {
  config.plugins.push(
    new webpack.IgnorePlugin(/redux-logger/)
  )

  config.plugins.push(
    new webpack.optimize.UglifyJsPlugin({
      compress: {
            warnings: false,
      },
      minimize: true
    })
  )
}
```

And remove the logger middleware from the store for production, e.g. in store.js: 

```
if (process.env.NODE_ENV !== 'production') {
    middleware = composeWithDevTools(
        applyMiddleware(
            thunk,
            cartMiddleware,
            session,
            logger(),
            queryMiddleware(getQueries, getEntities)
        )
    )
} else {
    middleware = applyMiddleware(
        thunk,
        cartMiddleware,
        session,
        queryMiddleware(getQueries, getEntities)
    )
}


export default createStore(
    reducer,
    initialState,
    middleware
);
```

**Comment by VaskaDogana** [comment]
Hi, how I can disable  logged some actions to be?
For example, I have action on hover in transport list. My be I can, write some like 
```
if(action.type == 'HOVER'){
return null
}
```

**How I connect logger:**

```
**import {createLogger} from 'redux-logger'
const logger = createLogger();


export default function createStore(initialState = {}) {
  const registry = new Registry(baseReducers)
  let finalCreateStore = applyMiddleware(registryMiddleware(registry), logger)**
```

**Comment by jfilter** [comment]
For people who doesn't what to use Webpack: https://stackoverflow.com/questions/41697346/how-to-separate-production-and-development-code-in-react-native

**Comment by EroticCode** [comment]
you can rewrite from  applyMiddleware( thunk ,  logger ) to pplyMiddleware( thunk )

**Comment by awnali** [comment]
I faced the same issue specifically with Android, then I changed the redux logger and HTTP logger to only run on dev server and my response time became 3 sec which was around 11 seconds before.


```
if (process.env.NODE_ENV !== 'production') {
  XMLHttpRequest = GLOBAL.originalXMLHttpRequest
    ? GLOBAL.originalXMLHttpRequest
    : GLOBAL.XMLHttpRequest;

  const loggerMiddleware = createLogger({
    predicate: (getState, action) => __DEV__,
  });
  middleWares = [...middleWares, loggerMiddleware];
}
```

**Comment by wkl007** [comment]
Thank you very much @slava-sh

**Comment by fardeen-panjwani** [comment]
> Here is a way not to apply the middleware at all:
> 
> ```js
> const middleware = [
>   ... other middleware ...
>   DEBUG && logger,
> ].filter(Boolean);
> const createStoreWithMiddleware = applyMiddleware(...middleware)(createStore);
> ```



> Here is a way not to apply the middleware at all:
> 
> ```js
> const middleware = [
>   ... other middleware ...
>   DEBUG && logger,
> ].filter(Boolean);
> const createStoreWithMiddleware = applyMiddleware(...middleware)(createStore);
> ```

Do I import DEBUG or what?

**Comment by eu81273** [comment]
```js
const logMiddleware = createLogger({predicate: () => process.env.NODE_ENV !== 'production'});
```

**Comment by louiCoder** [comment]
> ```js
> const logMiddleware = createLogger({
>   predicate: () => process.env.NODE_ENV !== 'production'
> });
> ```

This worked for me perfectly. Simplest solution

**Comment by jvidalv** [comment]
> ```js
> const logMiddleware = createLogger({
>   predicate: () => process.env.NODE_ENV !== 'production'
> });
> ```

The wrong thing about this approach is that the bundler tree shaking (Webpack, Parcel...) will not remove redux-logger from the code, as still in use, it just resolves to false when is asked if it has to log it or not. So the solution provided by @slava-sh is better as it will totally remove redux-logger from the code bundled in production.

**Comment by zhipengyan** [comment]
> > ```js
> > const logMiddleware = createLogger({
> >   predicate: () => process.env.NODE_ENV !== 'production'
> > });
> > ```
> 
> The wrong thing about this approach is that the bundler tree shaking (Webpack, Parcel...) will not remove redux-logger from the code, as still in use, it just resolves to false when is asked if it has to log it or not. So the solution provided by @slava-sh is better as it will totally remove redux-logger from the code bundled in production

I do like this

``` javascript
// webpack.config.js
module.exports = {
  //...
  resolve: {
    alias: {
      ...(process.env.NODE_ENV === "production"
        ? {}
        : {
            "redux-logger": path.resolve(
              __dirname,
              "path/to/fake-redux-logger.js"
            ),
          }),
    },
  },
};
```
