### ISSUE TITLE
How to use with TypeScript?

### ISSUE THREAD

**Issue by nizsheanez** [fcomb/redux-logger#89]
Try 1:
```
import createLogger = require('redux-logger')
console.log(createLogger)
let loggerMiddleware = createLogger()
```
Result: can't compile
```
error TS2349: Cannot invoke an expression whose type lacks a call signature.
```

Try 2: 
```
import createLogger from 'redux-logger'
console.log(createLogger)
let loggerMiddleware = createLogger()
```
Result: can compile but object is undefined in browser
```
undefined
Uncaught TypeError: redux_logger_1.default is not a function
```

Env: `webpack: 1.12.3`,  `ts-loader`
tsconfig.json:
```
"compilerOptions": {
    "target": "es5",
    "module": "commonjs",
    "jsx" :  "react",
    "sourceMap": true
  },
```

**Comment by nizsheanez** [comment]
solved by: 
```
"compilerOptions": {
    "target": "es6",
    "jsx" :  "react",
    "sourceMap": true
  },
```
but with es5 can't make it work.

**Comment by wkwiatek** [comment]
I just meet the same issue and solved it by doing: 
```js
import * as createLogger from 'redux-logger';
```
It compiles but still throws:
```
error TS2349: Cannot invoke an expression whose type lacks a call signature.
```

The line which causes damage is the last one in `lib/index.js`:
```js
module.exports = exports['default'];
```
Without this one it works with TypeScript exactly the same way as in docs.

**Comment by theaqua** [comment]
Why you import through `* as`? You need import it directly, `import createLogger from 'redux-logger'`.

**Comment by wkwiatek** [comment]
TypeScript default imports don't work for modules generated by babel.

You can find more info in discussion about it in TypeScript issue (based on `redux-logger` example): https://github.com/Microsoft/TypeScript/issues/5565.

**Comment by TheTedAdams** [comment]
I don't feel like changing target to es5 is a very good resolution to this issue. I'm worried about browser compatibility if I shift my compile target just to get this logger to work...

**Comment by TheTedAdams** [comment]
As a slightly better hacky solution I got the following to work:

`import createLogger = require('redux-logger');

const loggerMiddleware = (createLogger as any)();`

I can still target ES5 and I don't have any compiler errors.

**Comment by mjohnsonengr** [comment]
@ wkwiatek confirmed Microsoft/TypeScript#5565 outlines the problem well and includes two valid short-term fixes.  Thanks for linking us there :+1:

**Comment by maufarinelli** [comment]
thanks @TheTedAdams 
I just fixed using your better hack solution 
`import * as createLogger from 'redux-logger';
const logger = (createLogger as any)();`
