### ISSUE TITLE
More formatting of action messages

### ISSUE THREAD

**Issue by jacobrask** [fcomb/redux-logger#91]
In our application we send actions such as

    { type: 'FETCH_FOO', readyState: 'PENDING' }
    { type: 'FETCH_FOO', readyState: 'FULFILLED' }
    { type: 'FETCH_FOO', readyState: 'REJECTED' }

I have the logger collapsed, so I just see 'action FETCH_FOO' twice. I'd like to easily see the readyState of the action in the console. I made a private fork where I just set the different colors on the group labels, but it's hard coded for our use case.

Either all messages could be transformable and not just the action itself, or maybe the CSS (`%c`) arguments could be a setting.

**Comment by theaqua** [comment]
Done in [2.1.1](https://github.com/fcomb/redux-logger/releases/tag/2.1.1).
