### ISSUE TITLE
Deprecation without bumping a major

### ISSUE THREAD

**Issue by AugustinLF** [fcomb/redux-logger#96]
The 2.1.X deprecated transformer, without bumping a major. Since npm by default uses the [caret range](https://docs.npmjs.com/misc/semver#caret-ranges-1-2-3-0-2-5-0-0-4) method to know what it can update, this means that my app got full of console.error!

I don't exactly what the semver policy is, since this release didn't break anything, but just logged stuff, but then, perhaps a `console.warn` would have been more appropriated? Or bumping a major, but I agree that it would have been weird for just a deprecated message :)

Thanks for the good work anyway, if you'd like me to do a PR for that, I can do it!

**Comment by theaqua** [comment]
Just change `transformer` to `stateTransfomer`. If you see error instead of warn, you can do it faster :)

**Comment by AugustinLF** [comment]
Yes, I know, I got afraid and then changed the thing^^ Just thought it was not cool to scare people like that :p But no problem, thanks for the reactivity anyway!
