### ISSUE TITLE
Now exports an object instead of a function

### ISSUE THREAD

**Issue by tvararu** [fcomb/redux-logger#98]
```
TypeError: createLogger is not a function
```

Added a `console.log` to my project:

```javascript
var reduxLogger = require('redux-logger')

console.log(reduxLogger)

var finalCreateStore = compose(applyMiddleware(createLogger()))(createStore)
```

```
{ default: [Function: createLogger] }
```

**Comment by theaqua** [comment]
Hm, which version of babel do you use? Because 2.1.1 uses babel 6.
Check out [example](https://github.com/fcomb/redux-logger/blob/master/example/src/index.js#L6), with babel 6 everything is fine.

**Comment by tvararu** [comment]
That's the output in a fresh project, which doesn't use `babel` for the server-side, so the path it ends up requiring will be an already compiled `lib/index.js` that will `exports.default = createLogger`.

I get the feeling this may be due to the babel 6 transition rather than the package itself.

**Comment by jnv** [comment]
Agreed, we have project still using Babel 5 and Redux logger stopped working for us. Default export behaviour was intentionally changed in Babel 6: https://phabricator.babeljs.io/T2212

So to actually get `createLogger` function, you need to get `default` property, e.g.:

```
const createLogger = require('redux-logger').default
```

You should probably use [add-module-exports](https://github.com/59naga/babel-plugin-add-module-exports) plugin to maintain previous behaviour compatible with Babel 5 and CommonJS.

**Comment by theaqua** [comment]
Fixed, guys! By `add-module-exports`, as @jnv recommended.

[2.1.3](https://github.com/fcomb/redux-logger/releases/tag/2.1.3).

**Comment by tvararu** [comment]
Fast turnaround, thanks! :+1:

**Comment by jnv** [comment]
Thank you!
